### ISSUE TITLE
Spec deletion not working in practice

### ISSUE THREAD

**Issue by orta** [CocoaPods/trunk.cocoapods.org#162]
See: https://github.com/CocoaPods/CocoaPods/issues/4743

**Comment by orta** [comment]
So I think this: [GitHub.rb](https://github.com/CocoaPods/trunk.cocoapods.org/blob/master/app/models/github.rb#L38-L430) needs to use [these params](https://developer.github.com/v3/repos/contents/#delete-a-file)

**Comment by orta** [comment]
hrm, the SHA thing is tricky, [best recommendation](http://stackoverflow.com/questions/20207594/how-to-find-a-github-file-s-sha-blob) seems to be to curl the API for that file to get the base SHA: e.g. - https://api.github.com/repos/CocoaPods/Specs/contents/Specs/OrtaDeletePodTest/0.1.1/OrtaDeletePodTest.podspec.json

**Comment by keshavvishwkarma** [comment]
@orta Could you please suggest me what should I do to delete ``` pod "MyPodDemo" ```?. I have tried many time to delete it. but every time I have got an error 

``` $ pod trunk delete MyPodDemo 0.0.1 ``` 

WARNING: It is generally considered bad behavior to remove versions of a Pod that others are depending on!
Please consider using the `deprecate` command instead.
Are you sure you want to delete this Pod version?
> yes

[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later

After This I also tried to install this ``` pod "MyPodDemo" ``` into new project but found following error -
``` $ pod install  ``` $
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing MyPodDemo (0.0.1)

[!] Error installing MyPodDemo
[!] /usr/bin/git clone https://github.com/keshavvishwkarma/MyPodDemo.git /var/folders/fj/qnbzrkh954g74zybhnksd7840000gn/T/d20160110-2864-j2gu91 --single-branch --depth 1 --branch 0.0.1

Cloning into '/var/folders/fj/qnbzrkh954g74zybhnksd7840000gn/T/d20160110-2864-j2gu91'...
warning: Could not find remote branch 0.0.1 to clone.
fatal: Remote branch 0.0.1 not found in upstream origin

So I'm not able to understand that if ``` pod "MyPodDemo" ``` is not deleted successful then why it is not installing ? 

Actually I'm not much more familiar with pod It would be great for me If you tell me the steps or a way  to delete this library from pod if It is possible.

**Comment by segiddins** [comment]
@keshavvishwkarma it's a bug we have to fix on our side

**Comment by keshavvishwkarma** [comment]
@orta After run ` $ pod trunk delete MyPodDemo 0.0.1 `.  I try to create new pod library with help of command ` $pod lib create TestDemo `. It creates a library with error. Due to this the example does not configure with properly.


Running pod install on your new library.

[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `TestDemo_Tests`.. Updating CocoaPods might fix the issue.

 #  from /Users/keshav/Desktop/CocoaPods_ Skeleton/TestDemo/Example/Podfile:5
 #  -------------------------------------------
 #  
 >  target 'TestDemo_Tests', :exclusive => true do
 #    pod "TestDemo", :path => "../"
 #  -------------------------------------------

 Ace! you're ready to go!
 We will start you off by opening your project in Xcode
  open 'TestDemo/Example/TestDemo.xcworkspace'
The file /Users/keshav/Desktop/CocoaPods_ Skeleton/TestDemo/Example/TestDemo.xcworkspace does not exist.

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

### Not proper configration of pod by $pod lib create TestDemo 
It creates a directory structure but with its content but here ` TestDemo.xcworkspace `, ` Podfile.lock ` & ` Pods ` folder missing ...

>TestDemo
  ├── .travis.yml
  ├── _Pods.xcproject
  ├── Example
  │         ├── Podfile
  │         ├── TestDemo.xcodeproj
  │         └── Tests
   ├── LICENSE 
   ├── Pod
  │   ├── Assets
  │   └── Classes
  │     └── RemoveMe.[swift/m]
  └── README.md

**Comment by orta** [comment]
the `pod lib create` template is for 0.39, not 1.0.0 - please don't put off-topic comments in issues @keshavvishwkarma
