### ISSUE TITLE
Accidently pushed podspec with wrong capitals

### ISSUE THREAD

**Issue by jvanzummeren** [CocoaPods/trunk.cocoapods.org#181]
I accidently pushed the .podspec that has our library name without capitals.
I tried to push a new push spec with capitals (MarkyMark), but it's saying this name already exists.
Also tried doing trunk delete, but didn't help resolving the issue.

Is there any way we can still change the name of the library to the name with capitals?

Thanks in advance

**Comment by segiddins** [comment]
Changing the capitalization of an existing pod is unsupported, sorry

**Comment by jvanzummeren** [comment]
Ah ok, that's too bad. Since nobody is using this pod yet, is there any way you can help me remove the pod so i can retry? :)

**Comment by segiddins** [comment]
I can't remember if deleting all versions of the spec will let you change the case -- you might want to double check the trunk code to see if it will

**Comment by anowell** [comment]
I also have this problem. I pushed `algorithmia` a bit hastily before realizing capitalized pods are more common. Shortly after I deleted the published versions and tried to push with a rename, but still get the error that the name is taken. 

```
$ pod trunk info algorithmia
[!] No pod found with the specified name.
$ pod trunk info Algorithmia
[!] No pod found with the specified name.
```

```
$ pod trunk push Algorithmia.podspec
Updating spec repo `master`
Validating podspec
 -> Algorithmia (0.1.2)

[!] {"name"=>["is already taken"]}
```

As far as I can tell, I can only find mention of the pod name when doing `pod trunk me`, so I thought removing myself as an owner, might work, but removing owner for a non-existing package doesn't work either. Is it still the case that I'm basically stuff with the lowercase name (and no way to fully the podspec)? I wanted to check before we announce this, since changing it only gets harder after it actually gets usage.

**Comment by segiddins** [comment]
@anowell as I posted earlier, you'd have to check the code to be 100% sure, but it would appear so

**Comment by anowell** [comment]
At quick glance... it would seem publishing a version [creates a pod if it doesn't already exists here](https://github.com/CocoaPods/trunk.cocoapods.org/blob/be0a0cdbaf1f75b3c49a7823c6371a8e6f614952/app/controllers/api/pods_controller.rb#L154-L155), but [deleting a version only ever deletes that version](https://github.com/CocoaPods/trunk.cocoapods.org/blob/be0a0cdbaf1f75b3c49a7823c6371a8e6f614952/app/controllers/api/pods_controller.rb#L222).

It seems that after deleting a version there could be something like:

```
if pod.versions.count == 0
  pod.delete
end
```

@segiddins - I could probably find a bit of time to make and test such a change/PR if the general idea fits into the scope of trunk.cocoapods. Thoughts?

**Comment by anowell** [comment]
At closer glance, the [pod gets marked as `:deleted` if there are no versions](https://github.com/CocoaPods/trunk.cocoapods.org/blob/0557330ca3a2ea1636cfefc43e3c1e7f916b7b1c/app/models/pod_version.rb#L83). So I'm assuming there is a strong preference for marking as deleted rather than fully deleting (not surprising).

I can imagine a solution on-create that deletes if already marked 'deleted', right before recreating..

```ruby
DB.transaction do
    if pod&.deleted?
        pod.delete
        pod = nil
    end
    unless pod
            pod = Pod.create(:name => specification.name)
            pod.add_owner(@owner)
    end
    ...
```

but that seems a bit awkward just to support case renames... :-/

**Comment by segiddins** [comment]
Yeah, I don't think that'd be acceptable, because it wouldn't keep the namespace linked to the original owners

**Comment by anowell** [comment]
the latter example would keep 1 original owner intact (at least on the transaction level), and could be made to re-add all owners (probably not very elegant). I could try and propose a solution around explicitly checking for case difference on `trunk push` and actually updating the row with the new name (iff deleted - to avoid renaming pods that are being used).

But I sorta get the vibe that final world will more or less remain: "Changing the capitalization of an existing pod is unsupported, sorry." Should I just move on accept that my pod's capitalization isn't going to change?

**Comment by segiddins** [comment]
@anowell I think so, sorry

**Comment by orta** [comment]
There's also the fact that we keep file system representations. A change in case would mean a new folder, which isn't too bad - but it would also mean that people with case-insensitive file systems would break. Not sure it'd a good idea to support alas.
