### ISSUE TITLE
Deprecating pods puts them in the wrong place in Specs repo

### ISSUE THREAD

**Issue by andrew** [CocoaPods/trunk.cocoapods.org#212]
There are some pods showing up in the old layout of the Specs repo, looks like all of them are ones that have been recently deprecated so I'd guess the deprecate command hasn't been updated to handle the new layout?

![screen shot 2016-11-24 at 9 34 15 am](https://cloud.githubusercontent.com/assets/1060/20593335/e15f12a2-b229-11e6-9c04-f75b88049658.png)

**Comment by orta** [comment]
Thanks sir, that was enough to know what the problem is, the root behaviour is in https://github.com/CocoaPods/trunk.cocoapods.org/issues/211 

However, I think we'll have to look at deleting those new folders, so I'm keeping this open to represent that action

**Comment by andrew** [comment]
pinging @orta to clean up these folders now that the bug has been fixed

**Comment by orta** [comment]
Thanks - removed with https://github.com/CocoaPods/Specs/commit/7a8493c0d17d47bc618844cedf7ffad34e4a4555

@pallopmax @xtayga @GongChuanZan @malai520 @gianlucabertani @joselufo @jverkoey @tpinto @CheckRan  @ws00801526

I've removed duplicate and _unused_ podspecs for your libraries due to a trunk bug - I would recommend running the deprecate command again on your libraries, this time it should work correctly 👍 .
